/**
 * The shapes the engine hands the UI, one per read command.
 *
 * They are declared here rather than inferred at each call site because every
 * one of them crosses a JSON boundary (§4.9: JSON in, JSON out) and an
 * untyped boundary is where a UI quietly invents a field that does not exist.
 */

/**
 * One registry entry (`SAM --commands --json`, §4.8 P2). The palette lists
 * these, the menu bar is projected from them, and a control's `data-command` is
 * one of their ids — so a command that exists only in a menu is a diffable
 * finding rather than a dead click.
 */
export type CommandRead = {
  id: string;
  title: string;
  category: string;
  effect: 'read' | 'write' | 'presentation';
  params: ParamRead[];
  aliases: string[];
  planRequired: boolean;
  help: string;
  /** The declared UI anchor; the parity gate asserts membership in a closed set. */
  uiPlacement: string;
  /** The JSON identity of what the command edits (§4.8 P3). */
  jsonPath: string | null;
};

/**
 * One widget standing on a composed screen (COMPOSER §2.1): the surface key the
 * plan stores, and the width it takes in the stack's **two columns** — `2` is
 * the full canvas, `1` is half of it. The engine omits `span` for a full-width
 * widget, and everything the UI reads normalizes to this shape, so no caller has
 * to ask whether the member is there.
 */
export type ScreenComponent = { surface: string; span: 1 | 2 };

export type ParamRead = {
  name: string;
  type: string;
  flag: string | null;
  required: boolean;
  positional: boolean;
  repeats: boolean;
  help: string;
};
export type KeybindingRead = { key: string; command: string };

export type MenuItemRead = {
  id: string;
  title: string;
  category: string;
  effect: string;
  key: string | null;
};

export type MenuRead = { title: string; items: MenuItemRead[] };

/** `SAM --commands --json` — the registry, its menu projection and the keymap. */
export type CommandsRead = {
  commands: CommandRead[];
  menu: { menus: MenuRead[] };
  keybindings: KeybindingRead[];
};

/** One plan the picker can open (Appendix C.5's `several` phase). */
export type PlanRead = { name: string; path: string; revision: string };

/** `SAM paths --json` — where everything lives, and which plans exist. */
export type PathsRead = {
  dataDir: string;
  plansDir: string;
  indexesDir: string;
  resourcesDir: string;
  /** Null on a machine with no plan at all: `plans` carries the picker's list. */
  plan: string | null;
  layer: string | null;
  revision: string | null;
  plans: PlanRead[];
};

/** `SAM views --json` — the bootstrap: what exists and where it is reached from. */
export type ViewsRead = {
  views: Record<string, ViewDefRead>;
  navigation: Array<{ title: string; view: string; icon?: string | null }>;
  types: Record<string, TypeRead>;
  keybindings: KeybindingRead[];
  /** The app's own schema, generated by the same `FieldDef` the UI renders. */
  settings: FieldRead[];
  /** Advisory findings the loader published — reported, never recomputed (§3.7). */
  warnings: Diagnostic[];
  /** The settings screen's current values (`rules.json#/study`). */
  study: Record<string, unknown>;
  /** The identity washes: record id → one of the four rooms, by the plan's order. */
  washes?: Record<string, string>;
  /** The frame's context slot (R2): the plan's date, in the plan's timezone. */
  today?: TodayRead | null;
};

/**
 * The plan's own today — the one date fact the frame needs (UI_SPEC R2). The
 * engine resolves it (the plan owns the timezone) and hands the parts so no
 * screen parses an ISO string: `week` is the week record that covers today,
 * with the number of weeks beside it when the plan declares that.
 */
export type TodayRead = {
  date: string;
  day: number;
  month: string;
  weekday: string;
  week: { index: number; of: number | null } | null;
};

/**
 * One saved view as declared in `content/views.json` — the whole definition, so
 * the view editor edits the keys by name rather than rebuilding them (§4.8 P3).
 * `blocks` is `unknown[]` here on purpose: an unauthored key belongs to whatever
 * build wrote it, and the editor passes unknown keys back untouched.
 */
export type ViewDefRead = {
  /**
   * The kind this view reads — **absent on a composed screen** (COMPOSER §2.1),
   * which names widgets instead of a kind. A view must still draw something,
   * so the validator refuses one with neither `type` nor `components`.
   */
  type?: string | null;
  layout?: string | null;
  filter?: string | null;
  sort?: string | null;
  group?: string | null;
  limit?: number | null;
  columns?: string[] | null;
  nulls?: string | null;
  blocks?: Array<Record<string, unknown>> | null;
  /**
   * The screen's own composition (COMPOSER §2.1): one entry per widget, in the
   * student's order. Present — **even empty** — makes the view a composed
   * screen and takes precedence over `panel` and `blocks`; absent leaves the
   * view exactly as it was.
   *
   * `span` is the widget's width in the composed stack's two columns: `1` is
   * half, `2` is the full canvas, and an absent member means `2` (COMPOSER
   * §2.1's 2026-09-30 extension — the resize control on the frame writes it).
   */
  components?: Array<{ surface: string; span?: number }>;
  /**
   * The screen this destination is (P2): a view that declares a panel **is**
   * that screen — `today`, `reviews`, `progress` — and its blocks stay in the
   * file as the machine's own composition (D6).
   */
  panel?: string | null;
};

export type TypeRead = {
  /** `"identity"` marks the kinds the four washes paint (a course, a track). */
  colorRole?: string | null;
  icon: string | null;
  /** The parent type's name, when this kind nests inside another (§3.1). */
  parent?: string | null;
  trackable: boolean | null;
  pipeline: string | null;
  /** §6 Phase 7's private-record rule: these records stay out of a shared profile. */
  private?: boolean | null;
  fields: FieldRead[];
};

/** Complete field definition serialized by the engine (§4.8 P3). */
export type FieldRead = {
  key: string;
  type: string;
  label: string | null;
  to: string | null;
  options: string[] | null;
  cardinality?: string | null;
  required?: boolean | null;
  expr?: string | null;
  [extension: string]: unknown;
};

/** Engine system view payload (`SAM system.view --json`, S14, UI·P3/U6). */
export type MachineRead = {
  kinds: MachineKind[];
  views: MachineView[];
  destinations: MachineDestination[];
  /** `rules.json` exactly as the plan holds it — read, not re-shaped. */
  rules: Record<string, unknown>;
  pipelines: MachinePipeline[];
  metrics: MachineMetric[];
  /** The designed screens a destination can be given (the engine's closed set). */
  panels: string[];
  /** The block kinds a view can hold (the engine's closed set). */
  blockKinds: string[];
};

export type MachineKind = {
  id: string;
  /** The rail title that names it, when a destination opens one of its views. */
  title: string | null;
  icon: string | null;
  parent: string | null;
  trackable: boolean | null;
  pipeline: string | null;
  private: boolean | null;
  records: number;
  views: string[];
  fields: MachineField[];
};

export type MachineField = {
  key: string;
  label: string | null;
  type: string;
  to: string | null;
  options: string[] | null;
  expr: string | null;
  required: boolean | null;
  /** How many of the kind's views pin this column in their own `columns` list. */
  pinned: number;
};

export type MachineView = {
  name: string;
  /** Kind read by this view, or null for composed screens. */
  kind: string | null;
  /** Layout identifier, or null for composed screens. */
  layout: string | null;
  /** Component count, or null for non-composed screens. */
  components: number | null;
  panel: string | null;
  blocks: number;
  columns: string[] | null;
  filter: string | null;
  sort: string | null;
  group: string | null;
  limit: number | null;
  destinations: Array<{ title: string; icon: string | null }>;
  /** Other views whose blocks draw this one. */
  drawnBy: string[];
  /** Derived metrics that fold this one. */
  foldedBy: string[];
};

export type MachineDestination = {
  title: string;
  view: string;
  icon: string | null;
  kind: string | null;
  missing: boolean;
};

export type MachinePipeline = {
  name: string;
  stages: string[];
  gates: unknown;
  completeWhen: string | null;
  usedBy: string[];
};

export type MachineMetric = {
  name: string;
  label: string;
  view: string;
  expr: string | null;
  reduce: string | null;
  unit: string | null;
  viewMissing: boolean;
};

/** One record exactly as it is stored: `fields` and `links` are two namespaces (§3.1). */
export type RecordDoc = {
  schemaVersion?: number;
  id: string;
  type: string;
  fields: Record<string, unknown>;
  links?: Record<string, string[]>;
  /** Computed derived values evaluated by engine (§3.1, §4.4). */
  derived?: Record<string, unknown>;
};

/** `SAM view <name> --json` — a saved query's result. */
export type ViewRead = {
  view: string;
  /** Target kind read by view, or null for composed screens (COMPOSER §2.2). */
  type: string | null;
  layout: string;
  columns: string[];
  candidates: number;
  returned: number;
  records?: RecordDoc[];
  grouped?: boolean;
  groups?: Array<{ key: string | null; records: RecordDoc[] }>;
  /** Composed screen component list (COMPOSER §2.2). */
  components?: Array<{ surface: string; span?: number }>;
  /** ViewOutcome advisory findings (§3.7). */
  warnings?: Array<{ code: string; path: string; message: string }>;
  /** Resolved block tree nodes evaluated by engine (Phase 5, §4.4). */
  blocks?: BlockNode[];
  /** Rich panel layout surface if configured (`views.json#/views/<name>/panel`, Phase 6, D8). */
  panel?: string;
};

/** Resolved block node in a view block tree (§3.6, D8). */
export type BlockNode = {
  kind: string;
  /** Record blocks: the saved view drawn, the type it holds, its projection. */
  view?: string;
  type?: string;
  layout?: string;
  title?: string | null;
  columns?: string[];
  candidates?: number;
  returned?: number;
  records?: RecordDoc[];
  grouped?: boolean;
  groups?: Array<{ key: string | null; records: RecordDoc[] }>;
  /** `stat`: the fold, what it folded, and how many records it folded. */
  label?: string | null;
  expr?: string | null;
  reduce?: string | null;
  value?: unknown;
  of?: number;
  /** `chart`: the bucket key expression, the value expression, and the window. */
  x?: string | null;
  y?: string | null;
  days?: number | null;
  buckets?: Array<{ key: string; value: unknown }>;
  /** `callout`. */
  text?: string | null;
  /** Containers: `columns` children, `conditional`'s branch, `repeat` instances. */
  blocks?: BlockNode[];
  when?: string | null;
  matched?: boolean;
  instances?: Array<{ record: RecordDoc; blocks: BlockNode[] }>;
  /** The stated fallback: what this build does not know, and what it does. */
  unknown?: string;
  reason?: 'unknown-kind' | 'depth' | 'unknown-view' | string;
  message?: string;
  known?: string[];
  warnings?: Array<{ code: string; path: string; message: string }>;
};

/** A block's records, flattened — the same rule a grouped view follows. */
export function blockRows(node: BlockNode): RecordDoc[] {
  if (node.grouped && node.groups) return node.groups.flatMap((group) => group.records);
  return node.records ?? [];
}

/** One validation finding, as the loader publishes it. */
export type Diagnostic = {
  code: string;
  path: string;
  line: number | null;
  message: string;
  severity?: 'error' | 'warning';
};

/** The records a view returned, flattened. A grouped view is still one table. */
export function rowsOf(outcome: ViewRead): RecordDoc[] {
  if (outcome.grouped && outcome.groups) return outcome.groups.flatMap((group) => group.records);
  return outcome.records ?? [];
}

/** The design's own rule: a label, else the key. The key is never hidden. */
export function labelOf(field: FieldRead | undefined, key: string): string {
  if (!field) return key;
  return field.label && field.label.length > 0 ? field.label : key;
}

/** A record's own label: `title`, else `label`, else `name`, else its id (Appendix C.1). */
export function recordLabel(record: RecordDoc): string {
  for (const key of ['title', 'label', 'name']) {
    const value = record.fields[key];
    if (typeof value === 'string' && value.length > 0) return value;
  }
  // A kind whose own name for a row is something else (`term` on a vocabulary
  // word, `code` on a course) still reads as words in a review queue or a
  // picker: the first non-empty string field is a better label than an id, and
  // the id remains the fallback when there is no text at all.
  for (const value of Object.values(record.fields)) {
    if (typeof value === 'string' && value.length > 0) return value;
  }
  return record.id;
}

/**
 * A key spoken as a name: `today.topics` reads as “Today Topics” when the plan
 * gave the thing no title of its own (D2: a dotted id never reaches a screen).
 */
export function nameOf(key: string): string {
  return key
    .replace(/[._-]+/g, ' ')
    .replace(/\b\w/g, (letter) => letter.toUpperCase())
    .trim();
}

/**
 * One row of the day, exactly as `today.view` reports it (UI P2 · U1). The
 * `reason` line is composed by the engine from the same numbers beside it, so a
 * screen states the fact it was given instead of re-deriving one.
 */
export type TodayItem = {
  id: string;
  kind: string;
  label: string;
  course: { id: string; label: string; wash?: string } | null;
  dueDate: string | null;
  lateDays: number;
  est: number | null;
  reviewedDaysAgo: number | null;
  intervalDays: number | null;
  weekIndex: number | null;
  daysUntil: number | null;
  reason: string;
};

/** The six facts `today.view` states, in the fixed order the screen states. */
export type TodayGroupId = 'committed' | 'late' | 'due' | 'next' | 'stale' | 'upcoming';

export type TodayGroup = { id: TodayGroupId; count: number; items: TodayItem[] };

/** One day of the last seven, as the read reports it (oldest first). */
export type TodayDay = { date: string; weekday: string; day: number; loggedMin: number; isToday: boolean };

/** The day's facts — no ranking, no score (D1). */
export type TodayFacts = {
  date: string;
  weekday: string;
  day: number;
  month: string;
  week: { index: number | null; of: number | null; id: string | null };
  groups: TodayGroup[];
  totals: { plannedMin: number; loggedMin: number; targetMin: number | null };
  /** How many records the plan holds at all — `0` is the plan just created
      empty, which is a different screen from a plan with nothing due. */
  records: number;
  /** The last seven days, oldest first, ending on `date`. */
  days: TodayDay[];
  allClear: boolean;
  gap: { daysSince: number; since: string; waiting: number; estMin: number } | null;
};

/** One group of a day's facts, by id — undefined when the read has not landed. */
export function todayGroup(facts: TodayFacts | null, id: TodayGroupId): TodayGroup | undefined {
  return facts?.groups.find((group) => group.id === id);
}

/**
 * Minutes as a student says them: `45 min`, `4 h`, `4 h 15 min`. A session
 * length is never printed as `255`.
 */
export function durationText(minutes: number): string {
  const total = Math.max(0, Math.round(minutes));
  if (total < 60) return `${total} min`;
  const hours = Math.floor(total / 60);
  const rest = total % 60;
  return rest === 0 ? `${hours} h` : `${hours} h ${rest} min`;
}

/**
 * The reference a duration control offers — `controls.md` §4's own four.
 * One list, because every surface that offers a duration draws the same
 * control: an estimate is picked from these, or it is typed.
 */
export const DURATIONS = [15, 25, 45, 60];

/** The four washes are the identity system; nothing else may paint a course. */
export const WASHES = ['mint', 'lilac', 'butter', 'sky'] as const;

/**
 * A course's wash, by the plan's own order — the engine assigns it (it owns the
 * identity-role declaration and the record order), so two screens cannot paint
 * one course two ways. Absent means the plan declares no identity type.
 */
export function washOf(course: { wash?: string } | null | undefined): string | null {
  return course?.wash ?? null;
}
