// GENERATED by `node tools/presets.mjs --write` — the bundled starts, read off
// `Sources/SAMCore/Resources/presets/` (their README's own sentence and their
// records' own size). Do not edit by hand; `node tools/presets.mjs --check`
// (a gate in `tools/gates.mjs`) fails the moment this copy and the bundle
// disagree. Fields: the registry's `plan.new --preset` id, the display title,
// one sentence of what it holds, the plan's own work kind and its count, and the
// minutes that work plans.
export type BundledStart = {
  id: string;
  title: string;
  line: string;
  work: number;
  workLabel: string;
  minutes: number;
};

export const BUNDLED_STARTS: BundledStart[] = [
  { id: "jee", title: "JEE", line: "A complete two-year JEE (Main + Advanced) plan for Physics, Chemistry and Mathematics, where every chapter of the official syllabus is a unit, every sitting is a logged session,…", work: 17, workLabel: "topics", minutes: 790 },
  { id: "neet", title: "NEET", line: "A six-week, chapter-by-chapter NEET (UG) preparation plan: three subjects, one chapter spine each, a flip-loop topic queue, problem sets with a derived percentage, chapter tests…", work: 15, workLabel: "topics", minutes: 715 },
  { id: "cbse11-pcm", title: "CBSE 11 PCM", line: "One place to run the CBSE Class 11 board year for Physics (042), Chemistry (043) and Mathematics (041): every chapter named the way CBSE names it, the flip study loop with a proof…", work: 18, workLabel: "topics", minutes: 725 },
  { id: "university-term", title: "University term", line: "A generic, ready-to-edit one-term study plan for a Computer Science degree: four courses, their modules and topics, a learn → prove → anchor queue, assessments, projects and…", work: 16, workLabel: "topics", minutes: 635 },
  { id: "language", title: "Language", line: "Learn one language from its writing system to a working vocabulary by keeping every word, phrase and dialogue in a review queue that a real scheduler orders for you.", work: 22, workLabel: "words", minutes: 0 },
  { id: "self-study", title: "Self-study", line: "A self-directed learning plan — a few tracks (systems, algorithms, networking) broken into stages, worked through a flip loop where solving problems is the proof, with projects as…", work: 6, workLabel: "topics", minutes: 375 },
];
